#!/usr/bin/env bash
# Interactive installer for PSSL LunchPad (lab meeting RSVP & food app).
# Asks a few questions, writes .env, builds and starts everything.
set -euo pipefail
cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ask() { # ask "Question" "default" -> $REPLY
  local q="$1" def="${2-}"
  if [ -n "$def" ]; then read -r -p "$q [$def]: " REPLY; REPLY="${REPLY:-$def}"
  else read -r -p "$q: " REPLY; fi
}
rand() { openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

command -v docker >/dev/null || { echo "Docker is required but not installed. https://docs.docker.com/engine/install/"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required (docker compose ...)."; exit 1; }

bold "🚀 PSSL LunchPad installer"
echo

if [ -f .env ]; then
  ask "A .env already exists. Keep it and just (re)build? (y = keep / n = reconfigure)" "y"
  if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
    docker compose up -d --build
    bold "✅ Rebuilt and started with the existing .env"
    exit 0
  fi
fi

bold "— Web server —"
ask "Port to publish the web app on" "8080"; WEB_PORT="$REPLY"

ask "Use the bundled Caddy proxy for HTTPS on ports 80/443? (needs DNS + open ports) (y/N)" "n"
USE_CADDY="$REPLY"
if [ "$USE_CADDY" = "y" ] || [ "$USE_CADDY" = "Y" ]; then
  ask "Domain name for the app (e.g. food.pssl.mae.ufl.edu)"; DOMAIN="$REPLY"
  APP_URL="https://$DOMAIN"
else
  DOMAIN=""
  ask "Public URL members will use to reach the app" "http://$(hostname -f 2>/dev/null || hostname):$WEB_PORT"
  APP_URL="$REPLY"
fi

echo
bold "— WordPress SSO —"
echo "  (from Settings → PSSL SSO on the PSSL WordPress site;"
echo "   add the redirect URI $APP_URL/auth/wp/callback there)"
ask "WordPress base URL" "https://pssl.mae.ufl.edu"; WP_BASE_URL="$REPLY"
ask "Client ID"; WP_CLIENT_ID="$REPLY"
ask "Client Secret"; WP_CLIENT_SECRET="$REPLY"
ask "Admin emails (comma separated, may be empty — WP admins/editors are admins anyway)" ""; ADMIN_EMAILS="$REPLY"

echo
bold "— Discord bot (optional, can be added later by editing .env) —"
ask "Set up the Discord bot now? (y/N)" "n"
DISCORD_CLIENT_ID=""; DISCORD_CLIENT_SECRET=""; DISCORD_BOT_TOKEN=""; DISCORD_GUILD_ID=""; DISCORD_CHANNEL_ID=""
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
  echo "  (create an app at https://discord.com/developers/applications, add OAuth2"
  echo "   redirect $APP_URL/auth/discord/callback, and invite the bot to your server)"
  ask "Discord OAuth2 Client ID"; DISCORD_CLIENT_ID="$REPLY"
  ask "Discord OAuth2 Client Secret"; DISCORD_CLIENT_SECRET="$REPLY"
  ask "Discord Bot Token"; DISCORD_BOT_TOKEN="$REPLY"
  ask "Discord Server (guild) ID"; DISCORD_GUILD_ID="$REPLY"
  ask "Discord channel ID for reminders"; DISCORD_CHANNEL_ID="$REPLY"
fi

bold "Generating secrets and writing .env ..."
{
  echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "WEB_PORT=$WEB_PORT"
  echo "APP_URL=$APP_URL"
  echo "POSTGRES_PASSWORD=$(rand)"
  echo "SESSION_PASSWORD=$(rand)"
  echo "BOT_API_TOKEN=$(rand)"
  echo "WP_BASE_URL=$WP_BASE_URL"
  echo "WP_CLIENT_ID=$WP_CLIENT_ID"
  echo "WP_CLIENT_SECRET=$WP_CLIENT_SECRET"
  echo "ADMIN_EMAILS=$ADMIN_EMAILS"
  echo "DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID"
  echo "DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET"
  echo "DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN"
  echo "DISCORD_GUILD_ID=$DISCORD_GUILD_ID"
  echo "DISCORD_CHANNEL_ID=$DISCORD_CHANNEL_ID"
  echo "CHANNEL_REMINDER_HOURS=48"
  echo "DM_REMINDER_HOURS=24"
  if [ "$USE_CADDY" = "y" ] || [ "$USE_CADDY" = "Y" ]; then
    echo "COMPOSE_PROFILES=caddy"
    echo "DOMAIN=$DOMAIN"
  fi
} > .env
chmod 600 .env

echo
ask "Build and start now? (Y/n)" "y"
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
  docker compose up -d --build
  echo
  bold "✅ LunchPad is starting at $APP_URL"
  echo "   Reminder: the redirect URI $APP_URL/auth/wp/callback must be allowed"
  echo "   in the PSSL SSO plugin settings on WordPress."
else
  bold "Done. Start later with: docker compose up -d --build"
fi
