#!/usr/bin/env bash
# Interactive installer for PSSL LunchPad (lab meeting RSVP & food app).
# Asks a few questions, writes .env, builds and starts everything.
set -euo pipefail
cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ask() { # ask "Question" "default" -> $REPLY
  local q="$1" def="${2-}"
  if [ -n "$def" ]; then read -r -p "$q [$def]: " REPLY; REPLY="${REPLY:-$def}"
  else read -r -p "$q: " REPLY; fi
}
rand() { openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

command -v docker >/dev/null || { echo "Docker is required but not installed. https://docs.docker.com/engine/install/"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required (docker compose ...)."; exit 1; }

bold "🚀 PSSL LunchPad installer"
echo

if [ -f .env ]; then
  ask "A .env already exists. Keep it and just (re)build? (y = keep / n = reconfigure)" "y"
  if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
    docker compose up -d --build
    bold "✅ Rebuilt and started with the existing .env"
    exit 0
  fi
fi

bold "— How will members reach the app? —"
echo "  1) Behind Apache (or nginx) on this server  — recommended."
echo "     The app listens on a local port; you add a vhost that proxies to it."
echo "     An example Apache vhost is generated for copy & paste at the end."
echo "  2) Bundled Caddy container — serves HTTPS itself on ports 80/443"
echo "     (needs DNS pointing here and both ports free)."
echo "  3) Direct port access, plain HTTP — for testing only."
ask "Choose 1/2/3" "1"; MODE="$REPLY"

ask "Port the web app listens on (your proxy forwards to this)" "8080"; WEB_PORT="$REPLY"

USE_CADDY="n"; DOMAIN=""; WEB_BIND="127.0.0.1"
case "$MODE" in
  2)
    USE_CADDY="y"
    ask "Domain name for the app (e.g. food.pssl.mae.ufl.edu)"; DOMAIN="$REPLY"
    APP_URL="https://$DOMAIN"
    ;;
  3)
    WEB_BIND="0.0.0.0"
    ask "Public URL members will use" "http://$(hostname -f 2>/dev/null || hostname):$WEB_PORT"
    APP_URL="$REPLY"
    ;;
  *)
    MODE="1"
    ask "Public domain of the app (the vhost's ServerName, e.g. food.pssl.mae.ufl.edu)"; DOMAIN="$REPLY"
    APP_URL="https://$DOMAIN"
    echo "  → The app will bind to 127.0.0.1:$WEB_PORT (only reachable through Apache)."
    ;;
esac

echo
bold "— WordPress SSO —"
echo "  (from Settings → PSSL SSO on the PSSL WordPress site;"
echo "   add the redirect URI $APP_URL/auth/wp/callback there)"
ask "WordPress base URL" "https://pssl.mae.ufl.edu"; WP_BASE_URL="$REPLY"
ask "Client ID"; WP_CLIENT_ID="$REPLY"
ask "Client Secret"; WP_CLIENT_SECRET="$REPLY"
ask "Admin emails (comma separated, may be empty — WP admins/editors are admins anyway)" ""; ADMIN_EMAILS="$REPLY"

echo
bold "— Discord bot (optional, can be added later by editing .env) —"
ask "Set up the Discord bot now? (y/N)" "n"
DISCORD_CLIENT_ID=""; DISCORD_CLIENT_SECRET=""; DISCORD_BOT_TOKEN=""; DISCORD_GUILD_ID=""; DISCORD_CHANNEL_ID=""
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
  echo "  (create an app at https://discord.com/developers/applications, add OAuth2"
  echo "   redirect $APP_URL/auth/discord/callback, and invite the bot to your server)"
  ask "Discord OAuth2 Client ID"; DISCORD_CLIENT_ID="$REPLY"
  ask "Discord OAuth2 Client Secret"; DISCORD_CLIENT_SECRET="$REPLY"
  ask "Discord Bot Token"; DISCORD_BOT_TOKEN="$REPLY"
  ask "Discord Server (guild) ID"; DISCORD_GUILD_ID="$REPLY"
  ask "Discord channel ID for reminders"; DISCORD_CHANNEL_ID="$REPLY"
fi

bold "Generating secrets and writing .env ..."
{
  echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "WEB_PORT=$WEB_PORT"
  echo "WEB_BIND=$WEB_BIND"
  echo "APP_URL=$APP_URL"
  echo "POSTGRES_PASSWORD=$(rand)"
  echo "SESSION_PASSWORD=$(rand)"
  echo "BOT_API_TOKEN=$(rand)"
  echo "WP_BASE_URL=$WP_BASE_URL"
  echo "WP_CLIENT_ID=$WP_CLIENT_ID"
  echo "WP_CLIENT_SECRET=$WP_CLIENT_SECRET"
  echo "ADMIN_EMAILS=$ADMIN_EMAILS"
  echo "DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID"
  echo "DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET"
  echo "DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN"
  echo "DISCORD_GUILD_ID=$DISCORD_GUILD_ID"
  echo "DISCORD_CHANNEL_ID=$DISCORD_CHANNEL_ID"
  echo "CHANNEL_REMINDER_HOURS=48"
  echo "DM_REMINDER_HOURS=24"
  if [ "$USE_CADDY" = "y" ]; then
    echo "COMPOSE_PROFILES=caddy"
    echo "DOMAIN=$DOMAIN"
  fi
} > .env
chmod 600 .env

# ---------------------------------------------------------------- apache vhost
if [ "$MODE" = "1" ]; then
  VHOST_FILE="apache-vhost-$DOMAIN.conf"
  cat > "$VHOST_FILE" <<EOF
# PSSL LunchPad — Apache reverse-proxy vhost (generated by install.sh)
#
# Required modules:  sudo a2enmod proxy proxy_http headers ssl   (Debian/Ubuntu)
#                    (RHEL: modules are usually enabled in conf.modules.d)
# Then place this file in your vhost directory and reload Apache.
# Adjust the SSL certificate paths to your setup (UF cert or Let's Encrypt).

<VirtualHost *:443>
    ServerName $DOMAIN

    SSLEngine on
    SSLCertificateFile      /etc/ssl/certs/$DOMAIN.crt
    SSLCertificateKeyFile   /etc/ssl/private/$DOMAIN.key
    # SSLCertificateChainFile /etc/ssl/certs/$DOMAIN.chain.crt

    ProxyPreserveHost On
    ProxyPass        / http://127.0.0.1:$WEB_PORT/
    ProxyPassReverse / http://127.0.0.1:$WEB_PORT/

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port  "443"

    ErrorLog  \${APACHE_LOG_DIR}/lunchpad-error.log
    CustomLog \${APACHE_LOG_DIR}/lunchpad-access.log combined
</VirtualHost>

<VirtualHost *:80>
    ServerName $DOMAIN
    Redirect permanent / https://$DOMAIN/
</VirtualHost>
EOF
fi

echo
ask "Build and start now? (Y/n)" "y"
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
  docker compose up -d --build
  echo
  bold "✅ LunchPad is starting (app URL: $APP_URL)"
else
  bold "Done. Start later with: docker compose up -d --build"
fi

echo
if [ "$MODE" = "1" ]; then
  bold "──────────────────────────────────────────────────────────────"
  bold "NEXT STEP: add the Apache vhost (saved to ./$VHOST_FILE)"
  bold "──────────────────────────────────────────────────────────────"
  cat "$VHOST_FILE"
  bold "──────────────────────────────────────────────────────────────"
  echo "The app is only reachable through Apache (it binds to 127.0.0.1:$WEB_PORT)."
fi
echo "Reminder: allow the redirect URI  $APP_URL/auth/wp/callback"
echo "in the PSSL SSO plugin settings on WordPress."
