import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { db } from '../../../utils/db'
import { requireDbUser } from '../../../utils/auth'

// Printable attendance / signature sheet for food reimbursement.
export default defineEventHandler(async (event) => {
  await requireDbUser(event)
  const id = getRouterParam(event, 'id')!

  const meeting = await db.meeting.findUnique({
    where: { id },
    include: {
      caterer: true,
      guests: { orderBy: { name: 'asc' } },
      rsvps: { where: { attending: true }, include: { user: true } }
    }
  })
  if (!meeting) throw createError({ statusCode: 404, statusMessage: 'Meeting not found' })

  const participants = [
    ...meeting.rsvps.map((r) => r.user.name).sort((a, b) => a.localeCompare(b)),
    ...meeting.guests.map((g) => `${g.name} (guest)`)
  ]
  const rows = [...participants, ...Array(5).fill('')] // extra blank rows for walk-ins

  const dateStr = new Date(meeting.date).toLocaleString('en-US', {
    timeZone: 'America/New_York',
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit'
  })

  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  const pageWidth = 612 // US Letter
  const pageHeight = 792
  const margin = 54
  const rowHeight = 32
  const colNum = margin
  const colName = margin + 36
  const colSig = margin + 280
  const gray = rgb(0.45, 0.45, 0.45)
  const line = rgb(0.75, 0.75, 0.75)

  let page = doc.addPage([pageWidth, pageHeight])
  let y = pageHeight - margin

  // header
  page.drawText('Precision Space Systems Lab — Attendance Sheet', {
    x: margin, y, size: 16, font: bold
  })
  y -= 22
  page.drawText(meeting.title, { x: margin, y, size: 12, font: bold })
  y -= 16
  page.drawText(dateStr, { x: margin, y, size: 11, font })
  if (meeting.caterer) {
    y -= 15
    page.drawText(`Catering: ${meeting.caterer.name}`, { x: margin, y, size: 11, font })
  }
  y -= 24

  const drawTableHeader = () => {
    page.drawText('#', { x: colNum, y, size: 10, font: bold, color: gray })
    page.drawText('Name', { x: colName, y, size: 10, font: bold, color: gray })
    page.drawText('Signature', { x: colSig, y, size: 10, font: bold, color: gray })
    y -= 8
    page.drawLine({
      start: { x: margin, y },
      end: { x: pageWidth - margin, y },
      thickness: 1,
      color: rgb(0.2, 0.2, 0.2)
    })
    y -= rowHeight
  }
  drawTableHeader()

  rows.forEach((name, i) => {
    if (y < margin + 40) {
      page = doc.addPage([pageWidth, pageHeight])
      y = pageHeight - margin
      drawTableHeader()
    }
    page.drawText(String(i + 1), { x: colNum, y: y + 8, size: 11, font, color: gray })
    if (name) page.drawText(name, { x: colName, y: y + 8, size: 11, font })
    else {
      // blank walk-in row: line for the name too
      page.drawLine({
        start: { x: colName, y: y + 5 },
        end: { x: colSig - 20, y: y + 5 },
        thickness: 0.7,
        color: line
      })
    }
    page.drawLine({
      start: { x: colSig, y: y + 5 },
      end: { x: pageWidth - margin, y: y + 5 },
      thickness: 0.7,
      color: line
    })
    y -= rowHeight
  })

  y = Math.max(y, margin)
  page.drawText(
    'Sign-in sheet for food reimbursement · generated by PSSL LunchPad',
    { x: margin, y: margin - 20, size: 8, font, color: gray }
  )

  const bytes = await doc.save()
  const dateSlug = new Date(meeting.date).toISOString().slice(0, 10)
  setHeader(event, 'content-type', 'application/pdf')
  setHeader(event, 'content-disposition', `inline; filename="pssl-signin-${dateSlug}.pdf"`)
  return Buffer.from(bytes)
})
